#pragma once
#include <QMediaContent>
#include <QImage>
#include <QFile>
#include <taglib/tag.h>
#include <taglib/id3v2tag.h>
#include <taglib/mpegfile.h>
#include <taglib/mpegproperties.h>
#include <taglib/attachedpictureframe.h>
#include <taglib/popularimeterframe.h>
